import Head from "next/head";
import styles from '../styles/Home.module.css'
import Header from "../components/Header";
import Content from "../components/Content";



export default function Home(){
  return(
    <div className={styles.container}>
  <Head>
    <title>Dashboard</title> 
    <meta name="description" content="Generated by prince" />
    <link rel="icon" href="/favicon.ico" />
  </Head>

  <div className={styles.container}>
  
  <Header />
  <Content />
  </div>
 
    </div>
  )
}